<?xml version="1.0" encoding="UTF-8"?><testrun name="Test (1)" project="HawkClientTests" tests="3" started="3" failures="1" errors="0" ignored="0">
  <testsuite name="Tests.Test" time="0.248">
    <testcase name="testException" classname="Tests.Test" time="0.001"/>
    <testcase name="testGenerateAuthorizationHeader" classname="Tests.Test" time="0.238"/>
    <testcase name="testeGenerateAuthorizationHeaderWithPayload" classname="Tests.Test" time="0.009">
      <failure>
        <expected>Hawk id="100000004098766", ts="1374079796", nonce="09B8AFD6-B784-4981-ADD5-BEFF55C9E60D", hash="BtJQcST2BgfVHsmtXOopFzX2dJdZRwKMeuaj7nCcaQg=", ext="", mac="Sj78StVH2zGfmNbPEWZtie/nMyxGf2VCEO5oWvcBoZ8="</expected>
        <actual>Hawk id="100000004098766", ts="1374079796", nonce="09B8AFD6-B784-4981-ADD5-BEFF55C9E60D", hash="BtJQcST2BgfVHsmtXOopFzX2dJdZRwKMeuaj7nCcaQg=", ext="", mac="RJ3FpmvIW2A16Ri0rGCY+F5mwOvBd76jFWy4Mj1p52A="</actual>org.junit.ComparisonFailure: expected:&lt;...aQg=", ext="", mac="[Sj78StVH2zGfmNbPEWZtie/nMyxGf2VCEO5oWvcBoZ8]="&gt; but was:&lt;...aQg=", ext="", mac="[RJ3FpmvIW2A16Ri0rGCY+F5mwOvBd76jFWy4Mj1p52A]="&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at Tests.Test.testeGenerateAuthorizationHeaderWithPayload(Test.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
  </testsuite>
</testrun>
